[env]
TERM = "xterm-256color"
[general]
  import = ["tokyo-night.toml", "keybinds.toml"]

[window]
  opacity = 0.8
  blur = true
  startup_mode = "Fullscreen"

[font]
  normal = {family = "JetBrainsMono Nerd Font" }
  size = 15
  glyph_offset={x=0, y=0} 

[cursor]
  style = {shape="Block", blinking="on"}

[terminal]
  shell = {program="/bin/zsh"}
